apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: infinispan
  namespace: datagrid-demo
spec:
  replicas: 3

  # # Datagrid pod scheduling
  # scheduling:
  #   affinity:
  #     # This podAntiAffinity block is the default and it distributes the datagrid pods on all available cluster nodes
  #     podAntiAffinity:
  #       preferredDuringSchedulingIgnoredDuringExecution:
  #       - podAffinityTerm:
  #           labelSelector:
  #             matchLabels:
  #               app: infinispan-pod
  #               clusterName: infinispan
  #               infinispan_cr: infinispan
  #           topologyKey: kubernetes.io/hostname
  #         weight: 100
  #     # # This nodeAffinity can be added to select a group of cluster nodes using the node labels
  #     # nodeAffinity:
  #     #   requiredDuringSchedulingIgnoredDuringExecution:
  #     #     nodeSelectorTerms:
  #     #     - matchExpressions:
  #     #       - key: disktype
  #     #         operator: In
  #     #         values:
  #     #         - ssd

  # Datagrid statefulset application
  service:
    type: DataGrid

    # container:
    #   # Persistent storage (it's default because the default ephemeralStorage value is false)
    #   storage: 1Gi # This is the default
    #   storageClassName: my-storage-class # If it is not specified the default storageClass will be used
    #   # Ephemeral storage (alternative to Persistent storage)
    #   ephemeralStorage: true # Default is false

  container:
    # Datagrid Container Limits:Requests 
    memory: 350Mi:350Mi
    cpu: 500m:100m
    # # Datagrid extra JVM options (extraJvmOpts: "-<option>=<value>")
    # extraJvmOpts: "-Xlog:gc*:stdout:time,level,tags" # To log GC messages (they are not visible by default)

  # # Datagrid version
  # version: 8.5.5-2

  # # Datagrid upgrade
  # upgrades:
  #   type: Shutdown # or HotRodRolling

  # # Datagrid configuration
  # configMapName: "cluster-config"

  # # Datagrid Logging
  # logging:
  #   pattern: "%X{address} %X{user} [%d{dd/MMM/yyyy:HH:mm:ss Z}]" # Default is "%d{HH:mm:ss,SSS} %-5p (%t) [%c] %m%throwable%n"
  #   categories:
  #     org.infinispan: debug 
  #     org.jgroups: debug

  # Datagrid security section
  security:
    # Datagrid user authentication
    endpointAuthentication: true # enable the user authentication to access to the cluster data
    endpointSecretName: infinispan-generated-secret # auto-generated secret with user credentials

    endpointEncryption:
      # To encrypt connections between clients and Data Grid pods
      type: None # Use None value to disable client encryption
      # type: Service # Use None value to disable client encryption
      certSecretName: infinispan-cert-secret
      certServiceName: service.beta.openshift.io

      # Client certificate authentication
      clientCert: None # Possible values: Authenticate, Validate, None
      # clientCertSecretName: infinispan-client-cert-secret # The secret that contains the client trust store

    # Datagrid user authorization
    authorization:
      enabled: false # enable/disable the user authorization to access to the cluster data

  # Expose Datagrid to external clients
  expose:
    # Using a Route (the route will use encryption (https) or not (http) in base of the Datagrid encryption enabling/disabling respectively)
    type: Route
  #   host: www.example.org # optional route hostname (it can be autogenerated)
  #   # Using a NodePort
  #   # type: NodePort
  #   # nodePort: 30000 # node port
  #   # Using a LoadBalancer
  #   # type: LoadBalancer
  #   # port: 65535 # optional loadbalancer port
