apiVersion: infinispan.org/v2alpha1
kind: Batch
metadata:
  name: load-caches
  namespace: datagrid-demo
spec:
  cluster: infinispan
  config: |
    put --cache=distributed-cache hello world
    put --cache=distributed-cache ciao mondo
    put --cache=distributed-cache hola mundo
    put --cache=distributed-cache bonjour monde
    put --cache=distributed-cache hallo welt
    put --cache=distributed-cache olá mundo
    put --cache=distributed-cache こんにちは 世界
    put --cache=distributed-cache 你好 世界
    put --cache=distributed-cache привет мир
    put --cache=distributed-cache hej verden
    put --cache=distributed-cache merhaba dünya
    put --cache=distributed-cache marhabaan bialam
    put --cache=distributed-cache shalom olam
    put --cache=distributed-cache namaste duniya
    put --cache=distributed-cache hallo wêreld
    put --cache=distributed-cache sawasdee lok
    put --cache=distributed-cache yes sì
    put --cache=distributed-cache no nein
    put --cache=distributed-cache thank_you gracias
    put --cache=distributed-cache merci danke
    put --cache=distributed-cache please per_favore
    put --cache=distributed-cache arigato ありがとう
    put --cache=distributed-cache xiexie 谢谢
    put --cache=distributed-cache spasibo спасибо
    put --cache=distributed-cache obrigado de_nada
    put --cache=distributed-cache cat gatto
    put --cache=distributed-cache dog hund
    put --cache=distributed-cache chien perro
    put --cache=distributed-cache poisson fisch
    put --cache=distributed-cache wasser acqua
    put --cache=distributed-cache fire feu
    put --cache=distributed-cache earth terra
    put --cache=distributed-cache air aire
    put --cache=distributed-cache sky cielo
    put --cache=distributed-cache himmel ciel
    put --cache=distributed-cache sonne sole
    put --cache=distributed-cache moon lune
    put --cache=distributed-cache luna mond
    put --cache=distributed-cache red rouge
    put --cache=distributed-cache blue blau
    put --cache=distributed-cache green verde
    put --cache=distributed-cache giallo gelb
    put --cache=distributed-cache black noir
    put --cache=distributed-cache white blanco
    put --cache=distributed-cache kuro 黒
    put --cache=distributed-cache bai 白
    put --cache=distributed-cache food cibo
    put --cache=distributed-cache coffee kaffee
    put --cache=distributed-cache code кодекс
    put --cache=distributed-cache key schlüssel

    put --cache=replicated-cache hello world
    put --cache=replicated-cache ciao mondo
    put --cache=replicated-cache hola mundo
    put --cache=replicated-cache bonjour monde
    put --cache=replicated-cache hallo welt
    put --cache=replicated-cache olá mundo
    put --cache=replicated-cache こんにちは 世界
    put --cache=replicated-cache 你好 世界
    put --cache=replicated-cache привет мир
    put --cache=replicated-cache hej verden
    put --cache=replicated-cache merhaba dünya
    put --cache=replicated-cache marhabaan bialam
    put --cache=replicated-cache shalom olam
    put --cache=replicated-cache namaste duniya
    put --cache=replicated-cache hallo wêreld
    put --cache=replicated-cache sawasdee lok
    put --cache=replicated-cache yes sì
    put --cache=replicated-cache no nein
    put --cache=replicated-cache thank_you gracias
    put --cache=replicated-cache merci danke
    put --cache=replicated-cache please per_favore
    put --cache=replicated-cache arigato ありがとう
    put --cache=replicated-cache xiexie 谢谢
    put --cache=replicated-cache spasibo спасибо
    put --cache=replicated-cache obrigado de_nada
    put --cache=replicated-cache cat gatto
    put --cache=replicated-cache dog hund
    put --cache=replicated-cache chien perro
    put --cache=replicated-cache poisson fisch
    put --cache=replicated-cache wasser acqua
    put --cache=replicated-cache fire feu
    put --cache=replicated-cache earth terra
    put --cache=replicated-cache air aire
    put --cache=replicated-cache sky cielo
    put --cache=replicated-cache himmel ciel
    put --cache=replicated-cache sonne sole
    put --cache=replicated-cache moon lune
    put --cache=replicated-cache luna mond
    put --cache=replicated-cache red rouge
    put --cache=replicated-cache blue blau
    put --cache=replicated-cache green verde
    put --cache=replicated-cache giallo gelb
    put --cache=replicated-cache black noir
    put --cache=replicated-cache white blanco
    put --cache=replicated-cache kuro 黒
    put --cache=replicated-cache bai 白
    put --cache=replicated-cache food cibo
    put --cache=replicated-cache coffee kaffee
    put --cache=replicated-cache code кодекс
    put --cache=replicated-cache key schlüssel