apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01.datagrid-custom-config.yaml
  - 02.datagrid-cluster.yaml
  - 03.datagrid-distribuited-cache.yaml
  - 04.datagrid-replicated-cache.yaml
