apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01.datagrid-subscription.yaml
  - 02.grafana-subscription.yaml
  - 03.datagrid-operatorgroup.yaml
  - 04.grafana-operatorgroup.yaml
